### ISSUE TITLE
[Feature request] grouped in the context menu

### ISSUE THREAD

**Issue by Cammagno** [Erallie/css-inserter#2]
Nice plugin, I like it!

Please add an option to have the css names grouped inside the context menu, to avoid to clutter it when you have more than a few of them.

**Comment by Erallie** [comment]
That's a good idea! I will look into how to do that!

**Comment by Erallie** [comment]
@Cammagno I've implemented this. Can you test it out for me and let me know if it works?

**Comment by Cammagno** [comment]
> @Cammagno I've implemented this. Can you test it out for me and let me know if it works?

Works perfectly! Thanks!

**Comment by Erallie** [comment]
@Cammagno Wonderful! Thank you for using my plugin and reaching out to request this feature! I will close this issue now 😊

If you need anything else, feel free to create a new [issue](https://github.com/Erallie/css-inserter/issues) or comment on this issue again if it's related!
